#!/bin/sh -f
PBS_USER=root
PBS_JOBNAME=sgemm_testing
DBKEY=12345678
ROOT=`pwd`/../..
#start mf_server
${ROOT}/bin/mf/monitoring-server/start.sh

#start mf_agent
CONFIG=${ROOT}/bin/mf/monitoring-agent/dist/mf_config.ini
MF_START_BIN=${ROOT}/bin/mf/monitoring-agent/dist/start.sh
${MF_START_BIN} -i ${DBKEY} -c ${CONFIG}

#start testing on cpu
declare -a SIZE_ARRAY=(8 40 72 104 136 168 200 232)
N=1
ITER=10
EXECUTABLE=`pwd`/sgemm_mf_starpu

export STARPU_NCPU=1
export STARPU_NCUDA=0
export STARPU_NOPENCL=0
export STARPU_SCHED=dmda
export STARPU_CALIBRATE=1
sleep 5
for SIZE in "${SIZE_ARRAY[@]}"; do
	echo "$( date +'%c' ) ${EXECUTABLE} -x ${SIZE} -y ${SIZE} -z ${SIZE} -nblocks ${N} -iter ${ITER} -user ${PBS_USER} -task ${PBS_JOBNAME} -exp ${DBKEY}"
	${EXECUTABLE} -x ${SIZE} -y ${SIZE} -z ${SIZE} -nblocks ${N} -iter ${ITER} -user ${PBS_USER} -task ${PBS_JOBNAME} -exp ${DBKEY}
	echo "$( date +'%c' ): ending-------------------------------------------------------------------------------"
done

#start testing on gpu
export STARPU_NCPU=0
export STARPU_NCUDA=1
export STARPU_NOPENCL=0
export STARPU_SCHED=dmda
export STARPU_CALIBRATE=1
sleep 5
for SIZE in "${SIZE_ARRAY[@]}"; do
	echo "$( date +'%c' ) ${EXECUTABLE} -x ${SIZE} -y ${SIZE} -z ${SIZE} -nblocks ${N} -iter ${ITER} -user ${PBS_USER} -task ${PBS_JOBNAME} -exp ${DBKEY}"
	${EXECUTABLE} -x ${SIZE} -y ${SIZE} -z ${SIZE} -nblocks ${N} -iter ${ITER} -user ${PBS_USER} -task ${PBS_JOBNAME} -exp ${DBKEY}
	echo "$( date +'%c' ): ending-------------------------------------------------------------------------------"
done

#stop mf_agent
MF_STOP_BIN=${ROOT}/bin/mf/monitoring-agent/dist/stop.sh
${MF_STOP_BIN}

#stop mf_server
${ROOT}/bin/mf/monitoring-server/stop.sh